services:
  frontend:
    container_name: frontend
    ports:
      - '${VITE_SERVER_PORT}:${VITE_SERVER_PORT}'
    build:
      dockerfile: Dockerfile
    networks:
      - store-backend_store-network
networks:
  store-backend_store-network:
    external: true
