@startuml
start
repeat
    :Ingresar a página de inicio de sesión;
    :Click en botón recuperar credenciales;
    :Ingresar correo electrónico;
    if (¿Formato correcto?) is (Si) then
        :Click en botón recuperar;
        :Enviar correo electrónico con código;
        :Ingresar código;
        repeat
            :Ingresar contraseña;
            if (¿Formato correcto?) is (Si) then
                :Ingresar confirmación contraseña;
                if (¿Formato correcto?) is (Si) then
                    :Mostrar mensaje de éxito al cambiar contraseña;
                    end
                    note
                        caso de éxito
                    end note
                else (No)
                    :Mostrar mensaje de error;
                endif
            else (No)
                :Mostrar mensaje de error;
            endif
        repeat while()
    else (No)
        :Mostrar mensaje de error;
    endif
repeat while()
stop
@enduml
