@startuml
left to right direction
actor "usuario no identificado" as knownUSer
actor "Broker correos electrónicos" as broker
rectangle "recuperar credenciales" {
    usecase "Solicitar cambio de credenciales" as requestCredentials
    usecase "Enviar correo electrónico" as sendEmail
    usecase "Cambiar clave" as changePassword

    knownUSer -- requestCredentials
    requestCredentials .> sendEmail : include
    sendEmail ..> changePassword : include
    broker -- sendEmail
}
@enduml