@startuml
left to right direction
actor "usuario no identificado" as knownUSer

rectangle "Autenticación de usuarios" {
    usecase "Iniciar sesión" as login
    usecase "recuperar credenciales" as recoverCredentials

    knownUSer -- login
    knownUSer -- recoverCredentials
}
@enduml