@startuml
start
    :Ingresar página principal usuarios;
    repeat
        :Escribir en el campo de búsqueda;
        :Clic en el botón buscar;
        :Consultar usuarios con los criterios;
        if (¿consulta exitosa?) is (Si) then
            if (¿Se encuentran coincidencias?) is (Si) then
                :Filtrar tabla con las coincidencias;
                end
                note
                  Caso de éxito
                end note
            else (No)
                :Mostrar mensaje de que no hay coincidencias para los criterios;
            endif
        else (No)
            :Mostrar mensaje de error;
            note right
              Caso de error no controlado
            end note
        endif
    repeat while()
stop
@enduml

