name: frontend CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_OC_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_STORE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export VITE_SERVER_PORT=${{ secrets.VITE_SERVER_PORT }}
            export VITE_BACK_BASE_URL=${{ secrets.VITE_BACK_BASE_URL }}
            cd ${{ secrets.WORK_DIR }}
            [ ! -d "${{ secrets.WORK_DIR }}/store-frontend" ] && git clone https://github.com/an-tet/store-frontend.git
            cd store-frontend
            git pull
            touch .env
            sudo echo BACKEND_APP_PORT=${{ secrets.VITE_SERVER_PORT }} >> .env
            sudo echo POSTGRES_USER=${{ secrets.VITE_BACK_BASE_URL }} >> .env
            sudo docker stop $(sudo docker ps -a |  grep -E "frontend")
            sudo docker rm $(sudo docker ps -a |  grep -E "frontend")
            sudo docker rmi $(sudo docker images -a | grep -E "frontend")
            sudo docker compose up -d
